Resistance meter
memristor/mep3 pull request #113
Opened 2022-03-08 17:50 UTC by filiparag

- [x] Pretvoriti robota u Supervisor kontroler
- [x] TouchSensor na Dz rukama
- [x] URDF plugin ResistanceMeterDriver
- [ ] Ocitavanje i obrada sile dodira
- [ ] Emulacija merenja otpora na osnovu pozicije robota i sile dodira
- [ ] Objavljivanje otpora na topic
- [ ] BT cvor za ocitavanje otpora

2022-03-21 16:56 UTC, lukicdarkoo requested changes
Odlicno, samo ima nekoliko stvari da se pojednostavi

2022-03-21 16:56 UTC, lukicdarkoo commented on mep3_simulation/mep3_simulation/resistance_meter_driver.py
> +        self.__touch_sensor_back.enable(1)
Ovdje treba vrijednost timestep-a:
https://github.com/memristor/mep3/blob/eaa8736ebbdfcaf9e3b4804a0b00c897691df4ae/mep3_simulation/mep3_simulation/webots_dynamixel_driver.py#L38

2022-03-21 16:56 UTC, lukicdarkoo commented on mep3_behavior_tree/assets/strategies/excavation_squares_strategy.xml
> +<root main_tree_to_execute="BehaviorTree">
Mozes dodati da ovo bude parametar u robot_launch.py i simulation_launch.py

2022-03-21 16:56 UTC, lukicdarkoo commented on mep3_simulation/mep3_simulation/resistance_meter_driver.py
> +            y = axangle2euler((rot[0], rot[1], rot[2]), rot[3])[0] * 180 / pi
```suggestion
            yaw = math.degrees(rot[3])
```
- Uvijek imamo rotaciju oko z ose samo, tako da ti je yaw isto sto i rot[3]
- Za rad <-> deg citljivije je `math.radians/math.degrees`
- y -> yaw, ovako msm da je y koordinata :)

2022-03-21 16:56 UTC, lukicdarkoo commented on mep3_simulation/package.xml
> +  <exec_depend>tf_transformations</exec_depend>
Gdje se ovo koristi?

2022-03-21 16:56 UTC, lukicdarkoo commented on mep3_behavior_tree/include/mep3_behavior_tree/resistance_meter_action.hpp
> +        _Float32 tolerance;
Znam da je eksplicitnije ali mi izbija oci :D

2022-03-22 14:47 UTC, filiparag commented on mep3_behavior_tree/assets/strategies/excavation_squares_strategy.xml
> +<root main_tree_to_execute="BehaviorTree">
Dodao sam da mep3_bringup/simulation_launch.py ima `strategy` kwarg kom prosledis ime fajla bez ekstenzije, a podrazumevano je `first_startegy`.

2022-03-23 20:11 UTC, lukicdarkoo approved these changes

2022-03-23 22:21 UTC, VladimirVincan commented
Jesi proverio čemu služe ove rupe na Џ rukama? Neće neke žice izlaziti iz njih?
![image](https://user-images.githubusercontent.com/13640533/159805778-9acdb42a-dbec-4a0d-90f4-304c5532f3f9.png)

2022-03-23 22:26 UTC, filiparag commented
> Jesi proverio čemu služe ove rupe na Џ rukama? Neće neke žice izlaziti iz njih?

Za sada još ne znamo kako će izgledati merač, to je Kosta ostavio rupe da imamo za šta da ga pričvrstimo.

2022-03-23 23:51 UTC, lukicdarkoo approved these changes

2022-03-24 08:54 UTC, merged