Model diska
memristor/mep3 pull request #13
Opened 2021-11-14 19:23 UTC by filiparag

![image](https://user-images.githubusercontent.com/4471044/141695384-fd0a013d-f74a-4c6d-9765-77bd59b3277b.png)

2021-11-14 20:24 UTC, lukicdarkoo requested changes
Izgleda jako dobro, odlicno sto si se snasao sa PROTO fajlovima :)

Nekoliko detalja:
- [x] Folderi `libraries` i `plugins` vjerovatno nece biti potrebni, kada budu mozemo ih dodati.
- [x] Takodje, fajlovi `sample-half.stl`, `sample.stl` i `elements.svg` se ne koriste.
- [x] Ubaci nekoliko pakova na teren, cisto da studenti vide da postoje (tipa, Arbanas vec moze poceti viziju da radi)

2021-11-14 20:24 UTC, lukicdarkoo commented on mep3_simulation/webots_data/protos/Sample.proto
> +            geometry DEF MARKER_SHAPE_HALF IndexedFaceSet {
Odlicna ideja :)

2021-11-14 20:24 UTC, lukicdarkoo commented on mep3_simulation/webots_data/protos/Sample.proto
> +  field MFString   texture      "assets/samples/empty.png"
Ovo moze biti drop down:
https://github.com/cyberbotics/webots/blob/7e71add8b994ec6f5c0ba3c1d9689f300c778e23/projects/objects/backgrounds/protos/TexturedBackground.proto#L34-L35

2021-11-14 20:24 UTC, lukicdarkoo commented on mep3_simulation/webots_data/protos/Sample.proto
> +  field SFString   name         ""
```suggestion
  field SFString   name         "sample"
```
Neka ima neko podrazumjevano ime

2021-11-14 20:24 UTC, lukicdarkoo commented on mep3_simulation/webots_data/worlds/eurobot_2022.wbt
> +  position 1.1088129775047517 1.5966724740830898 1.5689008313620436
Ako nema potrebe, izbjegavaj mijenjati viewpoint, moze praviti kolizije. Jako mali detalj, nije previse bitno

2021-11-15 13:10 UTC, filiparag commented
![image](https://user-images.githubusercontent.com/4471044/141787487-761fb92d-bbd1-4be5-8255-7936ccfeefae.png)

- [x] Excavation sites
- [x] Playing area samples

2021-11-15 13:14 UTC, lukicdarkoo approved these changes
Hvala :)

2021-11-15 13:15 UTC, merged