Lynxmotion Webots driver, Lift command action
memristor/mep3 pull request #134
Opened 2022-03-25 13:24 UTC by VladimirVincan

https://user-images.githubusercontent.com/4471044/160135360-68b94ae7-dd6c-49d8-8c5a-b2a11014d194.mp4

2022-03-25 21:28 UTC, lukicdarkoo requested changes
Treba iskoristiti DynamixelDriver ovdje. Ovaj lift je samo jos jedna instanca Dynamixel drajvera

2022-03-25 23:19 UTC, VladimirVincan commented
> Treba iskoristiti DynamixelDriver ovdje. Ovaj lift je samo jos jedna instanca Dynamixel drajvera

Da promenimo naziv u RotationalMotorDriver recimo?

2022-03-26 20:38 UTC, filiparag commented
> Da promenimo naziv u RotationalMotorDriver recimo?

U ovom PR bih ostavio DynamixelDriver, da nam git blame posle ne bude necitljiv.

2022-03-28 10:51 UTC, lukicdarkoo approved these changes
Bojim se da ce nam dodavanje nove BT ackije otezati odrzavanje koda ali dobro je implementirano i ima odredjenih prednosti :)

2022-03-28 10:52 UTC, merged