Feature hardware interface
memristor/mep3 pull request #20
Opened 2021-11-17 18:07 UTC by angstrem98

Ros2 to motion board hardware interface implemented.
CAN Bus frames are received in a POSIX pthread instead of C++ std::thread. If we want to switch this thread to realtime, only pthreads can work in real time, not std::thread.
PID parameters for left and right wheel velocity regulators (inside motion board) are in `/mep3_driver/resource/mep3_big_config.urdf` file.

Encoder overflow detection is based on epuck driver by @lukicdarkoo with small changes.
This detection exists just to be safe, but encoder counter registers are 32 bit wide and overflow is practically impossible during a match.

2021-11-17 23:10 UTC, lukicdarkoo requested changes
Na prvi pogled odlicno izgleda. Sutra cu se malo bolje udubiti u detalje

2021-11-17 23:10 UTC, lukicdarkoo commented on mep3_driver/src/robot_hardware_interface.cpp
> +        std::cout << "speed_increments_right: " << speed_increments_right << std::endl;*/
```suggestion
```

Izbjegavaj komentarisati kod

2021-11-17 23:10 UTC, lukicdarkoo commented on mep3_driver/src/robot_hardware_interface.cpp
> +        mRightWheelPositionState = rightWheelRad;
```suggestion
        left_wheel_position_state_ = left_wheel_rad;
        right_wheel_position_state_ = right_wheel_rad;
```
S obzirom da tek krecemo projekat imas tu cast da odaberes konvenciju, ali mora biti konzistentno :)

2021-11-17 23:10 UTC, lukicdarkoo commented on mep3_driver/resource/mep3_big_ros2_control.yaml
> +      - hingejoint      # Non-actuated caster joint #2
```suggestion

```
Ovo je slucajno ostalo tu, moze se obrisati

2021-11-17 23:10 UTC, lukicdarkoo commented on mep3_driver/include/mep3_driver/motion_board_driver.hpp
> +class MotionBoardDriver
Primijetio sam da svi ROS paketi imaju svoj namespace, pa mozda ne bi bilo lose da i mi radimo isto

2021-11-18 10:36 UTC, lukicdarkoo requested changes
Sada sam malo dublje usao i izgleda dobro, samo molim te provjeri citanje, ovo ostalo su sitnice. Ovi za UR koriste `select` prije citanja:
https://github.com/ros-industrial/ur_modern_driver/blob/066716ed6a10eb0d9211f5bc5e32d65c7afce878/src/ur_communication.cpp#L126-L128

2021-11-18 17:16 UTC, angstrem98 commented on mep3_driver/src/motion_board_driver.cpp
> +        int nbytes = read(canbus_socket_, &frame, sizeof(struct can_frame));
Probao sam implementirati sa `poll` koji je moderna zamena za `select` (koji smatraju zastarelim). Nema razlike u CPU opterecenju. Ovaj `read` je podesen kao blokirajuci i ima svoj timeout. `poll` i `select` su namenjeni kad postoji vise socket-a, a u slucaju samo jednog nam ne treba.

2021-11-18 19:15 UTC, angstrem98 commented on mep3_driver/src/robot_hardware_interface.cpp
> +        std::cout << "speed_increments_right: " << speed_increments_right << std::endl;*/
Reseno

2021-11-18 19:15 UTC, angstrem98 commented on mep3_driver/src/robot_hardware_interface.cpp
> +        mRightWheelPositionState = rightWheelRad;
Sve prebaceno na underscore.

2021-11-18 19:15 UTC, angstrem98 commented on mep3_driver/resource/mep3_big_ros2_control.yaml
> +      - hingejoint      # Non-actuated caster joint #2
Obrisano.

2021-11-18 19:15 UTC, angstrem98 commented on mep3_driver/include/mep3_driver/motion_board_driver.hpp
> +class MotionBoardDriver
Stavljeno sve u namespace `mep3_driver`.

2021-11-18 19:16 UTC, angstrem98 commented on mep3_driver/include/mep3_driver/motion_board_driver.hpp
> +#include <unistd.h>
Komentarisano, a nesto prebaceno u .cpp.

2021-11-18 19:16 UTC, angstrem98 commented on mep3_driver/src/motion_board_driver.cpp
> +                right = protocol_unpack_int32(&frame.data[4]);
Sredjeno.

2021-11-18 19:16 UTC, angstrem98 commented on mep3_driver/src/motion_board_driver.cpp
> +	ioctl(canbus_socket_, SIOCGIFINDEX, &ifr_);
Nije bio taj razmak kod mene, ali sam formatirao ponovo.

2021-11-18 21:43 UTC, lukicdarkoo approved these changes
Hvala! Nadam se da ce raditi. Kalibraciju odometrije i peglanje u narednom PR-u

2021-11-19 14:02 UTC, merged