Trapezoidal trajectory generator (WIP)
memristor/mep3 pull request #26
Opened 2021-11-24 15:22 UTC by angstrem98

This is a generator for trajectories with trapezoidal velocity shape (bang-zero-bang control on acceleration level).
It is possible to generate a trajectory with non-zero final velocity (useful for chaining moves).
Interrupting current generation is possible by setting a new setpoint, but make sure to pass it current velocity.

Figure shows plots of position, velocity and acceleration. Max velocity and acceleration are 20 and 2, respectively.
First setpoint is -300. In time instant 10, new setpoint is commanded: +400. Velocity drops to zero and movement continues towards +400
![Figure_1](https://user-images.githubusercontent.com/44432285/143265936-2b042095-6599-4083-9e7d-90f1af029de0.png)
.

2021-11-25 10:25 UTC, lukicdarkoo commented
Ja sam mislio da je ovo ROS cvor. Ja bih da napravimo ROS cvor za kalibraciju odometrije i ovo integrisemo

2021-12-03 17:56 UTC, angstrem98 commented
Distance angle regulator sa osnovnim funkcijama dodat.

2021-12-04 13:16 UTC, lukicdarkoo requested changes
Prilicno dobro!

Na sastanku, moras mi samo objasniti kako kompenzuje gresku u uglu tokom linearnog kretanja.

2021-12-04 13:16 UTC, lukicdarkoo commented on mep3_navigation/src/distance_angle/distance_angle_regulator.cpp
> +    robot_angle_ = yaw;
S obzirom da imamo rotaciju samo oko z ose (yaw) Euler ugao bi trebalo da je jednak `2 asin (q_z)` (molim te provjeri):
```suggestion
    robot_angle_ = 2 * std::asin(q.z);
```

2021-12-24 09:35 UTC, angstrem98 commented on mep3_navigation/src/distance_angle/distance_angle_regulator.cpp
> +    robot_angle_ = yaw;
Ne moze, menjaju se `z` i `w`

2021-12-24 13:25 UTC, lukicdarkoo commented on mep3_navigation/src/distance_angle/distance_angle_regulator.cpp
> +    robot_angle_ = yaw;
Tvoje novo rjesenje je mnogo bolje. @angstrem98 mozes im ostaviti odgovor na ros.answers :)

2021-12-24 19:50 UTC, lukicdarkoo approved these changes
Hvala :)

2021-12-24 19:52 UTC, merged