Continuous integration
memristor/mep3 pull request #29
Opened 2021-12-01 21:26 UTC by filiparag

2021-12-01 22:50 UTC, lukicdarkoo commented
Ja nisam nikada koristio tu akciju samo ovu:
https://github.com/ros-industrial/industrial_ci

Mozemo probati, pa vidjeti kako ide. Ovo su kriticni dijelovi:
https://github.com/cyberbotics/webots_ros2/blob/c1b3a055f9b3d931066083e561c3dbee5b386c3a/.github/workflows/test.yml#L16-L17
Trebamo proveriti da li `ros-tooling/setup-ros` podrzava to

2021-12-01 22:51 UTC, lukicdarkoo commented on mep3_simulation/test/test_flake8.py
> -# Copyright 2017 Open Source Robotics Foundation, Inc.
Neka testira flake8 i pep257

2021-12-02 21:15 UTC, lukicdarkoo requested changes
Jako dobro, svidja mi se `ros-tooling/setup-ros`, moguce da je bolji od ros_industrial

Ne svidja mi se ideja da lintere pozivamo van standardnog ROS test sistema. Najekstremnije sto bih uradio je zamjena ament_flake8 sa flake8, ali u samim ROS testovima. 

Cak i ament_flake moze da se podesi sa `--config` flagom:
```
  --config path         The config file (default: /opt/ros/foxy/lib/python3.8/site-packages/ament_flake8/configuration/ament_flake8.ini)
```

Podrazumjevano podesavanje je:
```
[flake8]
extend-ignore = C816,D100,D101,D102,D103,D104,D105,D106,D107,D203,D212,D404,I202
import-order-style = google
max-line-length = 99
show-source = true
statistics = true
```
pa bih samo tu dodao izuzetke

2021-12-02 21:15 UTC, lukicdarkoo commented on .github/workflows/ci.yml
> +          sudo -E apt-get update
Zasto `sudo -E`? Da li je sudo uopste neophodan (obicno nije u CI, se ako akcija ne pravi neki Docker)

2021-12-02 21:15 UTC, lukicdarkoo commented on .github/workflows/linter.yml
> +        uses: suo/flake8-github-action@releases/v1
Ovo je malo cudno, lokalno, dio koda cemo testirati sa `colcon test`, dio sa flake8, a dio sa cppcheck/clang

2021-12-02 21:15 UTC, lukicdarkoo commented on .github/workflows/linter.yml
> +      - uses: shenxianpeng/cpp-linter-action@master
Ova akcija mi je malo sumnjiva, posljednji komit je bio prije 2 godine

2021-12-02 21:15 UTC, lukicdarkoo commented on .github/workflows/linter.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Ovo je kul, das im `GITHUB_TOKEN` i onda oni odmah komentarisu kod, ali nije konzistentno sa lokalnim testovima

2021-12-02 21:19 UTC, filiparag commented on .github/workflows/ci.yml
> +          sudo -E apt-get update
Treba nam zbog prosledjivanja `DEBIAN_FRONTEND` i drugih promenljivih. Pri instalaciji webots-a se pojavi `dialog` koji inace zapuca bez `-E` flaga. Radi konzistencije sam stavio na sve pozive `sudo` komande.

2021-12-02 21:22 UTC, filiparag commented on .github/workflows/linter.yml
> +      - uses: shenxianpeng/cpp-linter-action@master
[Poslednji komit](https://github.com/shenxianpeng/cpp-linter-action) je pre mesec dana 🤔
Mozda si pomesao forkove

2021-12-02 21:30 UTC, lukicdarkoo commented on .github/workflows/linter.yml
> +      - uses: shenxianpeng/cpp-linter-action@master
Ups, ja otvorio https://github.com/ArtificialAmateur/cpp-linter-action, moja greska

2021-12-07 20:02 UTC, lukicdarkoo approved these changes
Malo sam te vise iscimao, ali mislim da smo odradili kako treba. Hvala!

2021-12-07 20:03 UTC, merged