Robot arm
memristor/mep3 pull request #36
Opened 2021-12-13 23:04 UTC by VladimirVincan

2021-12-16 21:09 UTC, lukicdarkoo requested changes
Izgleda dobro, ali nesto se desilo sa meshevima, pa ne mogu da testiram :/

2021-12-16 21:09 UTC, lukicdarkoo commented on mep3_simulation/webots_data/protos/arm.protos
> +Solid {
Ovaj fajl izgleda kao visak

2021-12-16 21:09 UTC, lukicdarkoo commented on mep3_simulation/webots_data/protos/RobotArm.proto
> +              url ["assets/robot_arm_mesh/arm_mid.obj"]
Ovaj fajl koliko vidim ne postoji

2021-12-16 21:09 UTC, lukicdarkoo commented on mep3_simulation/webots_data/controllers/robot_arm/robot_arm.cpp
> +// You may need to add webots include files such as
Preimenuj kontroler u `test_robot_arm`. Svi test kontroleri neka pocinju sa `test_`

2021-12-16 21:09 UTC, lukicdarkoo commented on mep3_simulation/webots_data/worlds/eurobot_2022.wbt
> +}
Ovo nemoj dodavati u glavni wbt. Ako hoces, mozes napraviti novi wbt u kome imas samo ovog robota (bez Eurobot terena, samo Sample)

2021-12-17 00:31 UTC, VladimirVincan commented on mep3_simulation/webots_data/protos/RobotArm.proto
> +              url ["assets/robot_arm_mesh/arm_mid.obj"]
u gitignore je pisalo "ignoriši sve fajlove osim", nisam primetio da treba da se promeni

2021-12-17 14:17 UTC, lukicdarkoo submitted a review, later dismissed
Samo sam obrisao sam izvrsne fajlove, hvala :)

2021-12-22 15:56 UTC, lukicdarkoo commented
Radi i sa ROS-om! Samo vidi da decimiras .obj fajlove, smanjuj sve dok se ne pocne gubiti kvalitet:
https://docs.blender.org/manual/en/latest/modeling/modifiers/generate/decimate.html

2021-12-23 14:40 UTC, lukicdarkoo approved these changes
Super! Hvala :)

2021-12-23 15:00 UTC, merged