Upgrade opponent robots
memristor/mep3 pull request #84
Opened 2022-02-11 18:11 UTC by VladimirVincan

Added ArUco tags to robots. 
Enabled color swapping.
Aligned opponent robots.
Fixed Viewpoint position from:
- position 0.016513897535666677 0.2116180370445013 10.843371189226236

to:
- position 0 0 10

![image](https://user-images.githubusercontent.com/13640533/153645622-f2915b87-82ae-4ed6-bd01-ee2c54237244.png)
![image](https://user-images.githubusercontent.com/13640533/153645724-e466fb3b-236e-4c7b-bbe6-e5f935414f97.png)
![image](https://user-images.githubusercontent.com/13640533/153645667-7f0e8761-1e30-487f-b552-1976665c9967.png)

2022-02-11 22:22 UTC, MarijaGolubovic approved these changes

2022-02-12 10:22 UTC, lukicdarkoo requested changes
Odlicno!

Samo nesto cudno se desilo sa LFS-om

2022-02-12 10:22 UTC, lukicdarkoo commented on .gitattributes
> +*.png filter=lfs diff=lfs merge=lfs -text
Sta je ovo? :)

2022-02-12 10:22 UTC, lukicdarkoo commented on .gitattributes
> +*.png filter=lfs diff=lfs merge=lfs -text
Msm da si vratio LFS. Problem sa LFS-om je bio ogranicen protok (GitHub dozvoljava samo 1GB/m), pa smo ga morali ukloniti

2022-02-12 10:22 UTC, lukicdarkoo commented on mep3_simulation/webots_data/protos/OpponentBox.proto
> +  hiddenField SFColor purple_vec 0.360784 0.282353 0.541176
```suggestion
  field SFInt32    arucoNumber 1
  hiddenField SFColor yellowVector 0.972549 0.694118 0.0666667
  hiddenField SFColor purpleVector 0.360784 0.282353 0.541176
```
U Webots-u koriste camel-case bez skracenica pa mozemo i mi tako

2022-02-13 00:46 UTC, lukicdarkoo commented on mep3_simulation/webots_data/protos/OpponentBox.proto
> +            translation 0 0 0.01
Mozda da se podigne jos samo malo, sada sam primijetio da se desava z-fighting ponekad

2022-02-19 15:07 UTC, lukicdarkoo approved these changes

2022-02-19 15:07 UTC, merged