Go straight to the destination
memristor/mep3 pull request #93
Opened 2022-02-24 13:07 UTC by MarijaGolubovic

2022-02-24 14:42 UTC, lukicdarkoo requested changes
I dalje imamo problema sa rotacijom :/ Robot treba polako da se rotira prema cilju (u mjestu) i onda samo pravo

2022-02-27 17:22 UTC, MarijaGolubovic commented
Da li je u redu da ovako organizujem FSM ili si imao nesto drugacije u vidu?

2022-02-28 21:55 UTC, lukicdarkoo commented
> Da li je u redu da ovako organizujem FSM ili si imao nesto drugacije u vidu?

To je to (nisam testirao). Molim te dodaj da se roboti krecu malo cesce (ja sam stavio da stoje na zadatku 1-2s), do ponekad stanu negdje kod centra terena i dodaj jednu tacku na drugoj strani terena

2022-03-02 22:03 UTC, lukicdarkoo requested changes
Odlicno! Jos neke manje detalje sam dodao.

P.S. Uspori jos linearno kretanje i obrzaj rotaciju

2022-03-03 13:48 UTC, lukicdarkoo submitted a review, later dismissed
Odlicno, hvala! :)

2022-03-03 15:54 UTC, merged